# Change baseurl before deploy
baseurl = "https://shaddocknh3.github.io/"
languageCode = "zh-cn"
title = "ShaddockNH3"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

# Enable RSS full content
rssLimit = 20
enableRobotsTXT = true

[pagination]
pagerSize = 5