# Chinese language configuration
languageName = "简体中文"
languageDirection = "ltr"
title = "ShaddockNH3"
weight = 1

[params]
description = "技术、文学与哲学的交汇之地"

[params.sidebar]
subtitle = "Just a humble and obscure soul, dreaming of ascending to prominence while journeying along the path."
