# 多语言配置
# Hugo 多语言支持
# 详细配置见 languages.zh-cn.toml, languages.en.toml, languages.ja.toml

[zh-cn]
languageName = "简体中文"
languageDirection = "ltr"
title = "ShaddockNH3"
weight = 1

[en]
languageName = "English"
languageDirection = "ltr"
title = "ShaddockNH3"
weight = 2

[ja]
languageName = "日本語"
languageDirection = "ltr"
title = "ShaddockNH3"
weight = 3
