# Japanese language configuration
languageName = "日本語"
languageDirection = "ltr"
title = "ShaddockNH3"
weight = 3

[params]
description = "技術、文学、哲学の交差点"

[params.sidebar]
subtitle = "Just a humble and obscure soul, dreaming of ascending to prominence while journeying along the path."
