# Configure main menu and social menu

# 归档、关于和友链页面会自动从页面的 front matter 中读取菜单配置

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/ShaddockNH3"

[social.params]
icon = "brand-github"

[[social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"

[social.params]
icon = "rss"
